# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "@vagrant.basebox.name@"

  # Enable the Puppet provisioner
  config.vm.provision :puppet

  # Share
  config.vm.share_folder "share", "/home/vagrant/share", "/tmp"
end
